steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'video-ad-generator'
      - '--source=.'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars=OPENAI_API_KEY=${_OPENAI_API_KEY},GOOGLE_AI_API_KEY=${_GOOGLE_AI_API_KEY},ANTHROPIC_API_KEY=${_ANTHROPIC_API_KEY},RUNWAY_API_KEY=${_RUNWAY_API_KEY},GOOGLE_CLOUD_PROJECT=ai-tools-484419,FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY},FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN},FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID},FIREBASE_STORAGE_BUCKET=${_VITE_FIREBASE_STORAGE_BUCKET},FIREBASE_MESSAGING_SENDER_ID=${_VITE_FIREBASE_MESSAGING_SENDER_ID},FIREBASE_APP_ID=${_VITE_FIREBASE_APP_ID}'
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1200s'
